name: Auto merge main to dev
on: 
  pull_request:
    branches: [ main ]
    types: [closed]
jobs:
  merge-main-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: development
      - name: Auto-Merge Pull Request
        uses: reitermarkus/automerge@v2.6.0
